title: Nell's Portfolio
description: >-
  Senior Technical Writer
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

# Just the Docs settings
color_scheme: light

# Optional: Enable navigation
nav_enabled: true
nav_sort: case_insensitive
nav: show_all

# Enable or disable heading anchors
heading_anchors: true
