site_name: Nell Gram | Documentation Portfolio
site_url: https://nellcgram.github.io/
use_directory_urls: false
nav:
  - Home: index.md
  - Writing Samples:
    - Help Center Article: help-article.md
    - KB Article: kb-article.md
    - Release Notes: release-notes.md
    - EOB Guide: eob-guide.md
  - About This Site: about-this-site.md